# Generated by Django 5.0.7 on 2024-08-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_directmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
